### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by mrranstrom** [arcuru/faxyourballs#1]
I have some complaints to fax!

I think the upload is kinda broken.

On Android Chrome, I get stuck in the photo picker.

On desktop Chrome, when I pick a file and click Open, it reopens the image picker. When I pick a file and click Open again, it works. But clicking the image doesn't make the image bigger. Also I think the rendering is off - my newly uploaded image doesn't scroll with the rest of the page; it always draws in the same spot on the screen.

And do you even support IE6?

**Comment by arcuru** [comment]
> my newly uploaded image doesn't scroll with the rest of the page; it always draws in the same spot on the screen.

I don't want to touch your balls, so I'm not moving them.

> And do you even support IE6?

Only on original hardware.

**Comment by arcuru** [comment]
Closing. Works on my machine.
